### ISSUE TITLE
[Feat] 외부 저장소에서 Image load #11

### ISSUE THREAD

**Issue by Gnoam-R** [Gnoam-R/dogdom#11]
## 📌  Feature Issue
앱의 외부 저장소로 부터 이미지 데이터를 가져와 로컬에 저장 시킬것
내부 저장소로는 Room 라이브러리를 사용, 외부 저장소에 대한 접근 권한 요청 추가

## 📝  To-do

- [ ] 외부 저장소 접근 & 이미지 로드 후 내부 저장소에 저장
- [ ] 객체지향 프로그래밍을 준수
- [ ] 접근 권한 요청 추가
