### ISSUE TITLE
[Feat] 홈 화면의 서치바 검색 기능 추가 #7

### ISSUE THREAD

**Issue by Gnoam-R** [Gnoam-R/dogdom#7]
## 📌  Feature Issue
파이어베이스 기반으로 서버 DB로 부터 가져오는 데이터를 Local DB로 가져와 일시 저장 및 서치바로 검색되는 리스트를 뽑아내는 기능 구현

## 📝  To-do

- [ ] 파이어 베이스 기반 서버 송수신  확인
- [ ] 서치바 UI 연동
- [ ] Local DB에 데이터 일시 저장
